name: Lint, test and security scan
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  page_build:
  release:
    types:
      - created

jobs:
  check_bash_installer:
    name: Bash shell lint check
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Bash shell lint check with shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: error
          pattern: '*.sh'
          path: '.'
          exclude: './test/*'

  check_yaml:
    name: YAML lint check
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: 'Yaml lint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: './*.yaml*'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check_dotnet:
    name: .NET lint, test and build check
    runs-on: ubuntu-16.04
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create Dotnet environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100' # SDK Version to use.

      - name: Restore cached nuget packages
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Dotnet lint install dotnet-format for linting
        run: dotnet tool install -g dotnet-format --version 3.3.111304

      - name: Dotnet lint install report generator
        uses: xt0rted/dotnet-format-problem-matcher@v1

      - name: Dotnet lint check with dotnet-format
        run: dotnet format  --folder AKSKubeAuditReceiverSolution/ --check --dry-run  || true

      - name: Dotnet build solution
        run: dotnet build AKSKubeAuditReceiverSolution/AKSKubeAuditReceiver.sln

      - name: Dotnet test solution
        run: dotnet test AKSKubeAuditReceiverSolution/AKSKubeAuditReceiver.sln

  sysdig_dockerfile_cis_benchmark:
    name: Sysdig Dockerfile CIS benchmark
    needs: [check_bash_installer, check_yaml, check_dotnet]
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Sysdig CIS dockerfile benchmark
        uses: sysdiglabs/benchmark-dockerfile@v1.0.0
        id: cis_dockerfile_benchmark
        with:
          directory: './AKSKubeAuditReceiverSolution/AKSKubeAuditReceiver/'
          dockerfilePattern: 'Dockerfile'
          disallowedPackages: 'netcat'
          secretPatterns: 'aws_secret,pass'    
      - name: Post run Sysdig CIS dockerfile benchmark
        env:
          SYSDIG_SECURE_TOKEN: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
          PR_OWNER: ${{ github.event.pull_request.head.user.login }}
        run: |
          echo "###"
          echo "{\"pr_name\": \"${PR_TITLE}\", \"pr_sha\": \"${PR_SHA}\", \"pr_owner\": \"${PR_OWNER}\"}" > /tmp/report.json
          echo ${{ toJSON(steps.cis_dockerfile_benchmark.outputs.violation_report) }} > /tmp/report
          reportString=$(sed 's/"/\\"/g' /tmp/report)
          echo $reportString
          
          # send result to Sysdig monitor
          curl -X POST -s https://app.sysdigcloud.com/api/events -H 'Content-Type: application/json; charset=UTF-8' -H 'Authorization: Bearer '"${SYSDIG_SECURE_TOKEN}"'' -d '{"event":{"name":"CIS Dockerfile Benchmark - PR: '"${PR_TITLE}"' ","description":"'"${reportString}"'","severity":"6"}}' --compressed
          echo "###"

  sysdig_image_scan_forwarder:
    name: Sysdig image scan - Forwarder
    needs: [check_yaml, check_dotnet]
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2      
      - name: Build the Docker image
        run: docker build -f ./AKSKubeAuditReceiverSolution/AKSKubeAuditReceiver/Dockerfile ./AKSKubeAuditReceiverSolution --tag sysdiglabs/aks-audit-log-forwarder
      - name: Sysdig Secure inline image scan
        uses: sysdiglabs/scan-action@v2
        with:
          image-tag: "sysdiglabs/aks-audit-log-forwarder"
          sysdig-secure-token: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}

    sysdig_image_scan_installer:
      name: Sysdig image scan - Installer
      needs: [check_bash_installer]
      runs-on: ubuntu-16.04
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2      
        - name: Build the Docker image
          run: docker build -f ./build . --tag sysdiglabs/aks-audit-log-installer
        - name: Sysdig Secure inline image scan
          uses: sysdiglabs/scan-action@v2
          with:
            image-tag: "sysdiglabs/aks-audit-log-forwarder:auto"
            sysdig-secure-token: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}
